# -*- coding: utf-8 -*-
"""prepare_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s94hUQiysmR3j7s6yIquIvTSjROR_Jxj
"""

import os
import string
import gzip
nii_files = []
for dirpath, sf, files in os.walk('MICCAI_BraTS2020_TrainingData'):
    for file in files:
        if 'flair.nii.gz' in file:
            nii_files.append(os.path.join(dirpath,file))
            
nii_files

len(nii_files)

# put all gzip flair file into folder 'flair'
from shutil import copyfile
for item in nii_files:
    filename = os.path.basename(item)
    copyfile(item, os.path.join("MICCAI_BraTS2020_TrainingData/flair", filename))

# put all unzip flair file into folder 'flair2'
for i in nii_files:
    decompressed_file = gzip.open(i)
    out_path = i.replace('/','_')[:-3]
    with open('flair2/' + out_path, 'wb') as outfile:
        outfile.write(decompressed_file.read())